sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]

sonata_admin:
  show_mosaic_button: false
  dashboard:
    groups:
      sonata.admin.group.sponsored:
        label_catalogue: messages
        icon:            '<i class="fa fa-home"></i>'
        items:
          - App\Admin\InstitutionAdmin
          - App\Admin\ChildAdmin

      sonata.admin.group.publication:
        label_catalogue: messages
        icon: '<i class="fa fa-users"></i>'
        items:
          - App\Admin\CategoryAdmin
          - App\Admin\NewsAdmin