zend_extension=xdebug.so
;нужно чтобы пхп загрузил расширение xdebug при запуске интерпретатора
xdebug.mode=develop,coverage,debug
xdebug.start_with_request=yes
xdebug.idekey=PHPSTORM
xdebug.client_port=9003
xdebug.client_host=host.docker.internal
; либо 172.17.0.1 обычно

memory_limit = 512M
;нужно чтобы кэш нормально в симфони чистился (дохуя ему памяти надо Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes))
