zend_extension=xdebug.so
;нужно чтобы пхп загрузил расширение xdebug при запуске интерпретатора
xdebug.mode=develop,coverage,debug
xdebug.start_with_request=yes
xdebug.idekey=PHPSTORM
xdebug.client_port=9003
xdebug.client_host=host.docker.internal
; либо 172.17.0.1 обычно
