Group:
  type: object
  inherits: [ Resource, Timestamp ]
  config:
    interfaces:
      - ResourceInterface
      - TimestampInterface
    fields:
      name:
        type: String!
      description:
        type: String!
      institution:
        type: Institution!
      children:
        type: '[Child!]'
