# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    admin.news:
        class: App\Admin\NewsAdmin
        tags:
            - {
                name: sonata.admin,
                model_class: App\Entity\News,
                manager_type: orm,
                label: 'admin.news',
                label_translator_strategy: 'sonata.admin.label.strategy.underscore'
            }

    admin.category:
        class: App\Admin\CategoryAdmin
        tags:
            - {
                name: sonata.admin,
                model_class: App\Entity\Category,
                manager_type: orm,
                label: 'admin.category',
                label_translator_strategy: 'sonata.admin.label.strategy.underscore'
            }

    admin.institution:
        class: App\Admin\InstitutionAdmin
        tags:
            - {
                name: sonata.admin,
                model_class: App\Entity\Institution,
                manager_type: orm,
                label: 'admin.institution',
                label_translator_strategy: 'sonata.admin.label.strategy.underscore'
            }

    admin.group:
        class: App\Admin\GroupAdmin
        tags:
            - {
                name: sonata.admin,
                model_class: App\Entity\Group,
                manager_type: orm,
                label: 'admin.group',
                label_translator_strategy: 'sonata.admin.label.strategy.underscore'
            }

    admin.children:
        class: App\Admin\ChildAdmin
        tags:
            - {
                name: sonata.admin,
                model_class: App\Entity\Child,
                manager_type: orm,
                label: 'admin.child',
                label_translator_strategy: 'sonata.admin.label.strategy.underscore'
            }
